### ISSUE TITLE
adding a /show_recipient function to the bot

### ISSUE THREAD

**Issue by Colon101** [Luciism/enotify#4]
not a complex issue just need some help deploying the project locally so i can make a pr

**Comment by Luciism** [comment]
Can you provide some more details?

**Comment by Colon101** [comment]
> Can you provide some more details?

just need some help starting development

**Comment by Luciism** [comment]
> just need some help starting development
With what? 💀

Docs are available at https://enotify-docs.lucism.dev/self-host
